/* Generated By:JavaCC: Do not edit this line. LogoGramConstants.java */
package fr.esiea.main.grammaire;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LogoGramConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NOMBRE = 1;
  /** RegularExpression Id. */
  int MC_REPETE = 2;
  /** RegularExpression Id. */
  int MOT = 3;
  /** RegularExpression Id. */
  int LBRACKET = 4;
  /** RegularExpression Id. */
  int RBRACKET = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NOMBRE>",
    "\"REPETE\"",
    "<MOT>",
    "\"[\"",
    "\"]\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\";\"",
    "\"=\"",
    "\":\"",
  };

}
